check process dedupe pidfile "/mnt/HD/HD_a2/Nas_Prog/dedupe/dedupe.pid"
	start program = "/bin/sh /mnt/HD/HD_a2/Nas_Prog/dedupe/start.sh /mnt/HD/HD_a2/Nas_Prog/dedupe" with timeout 60 seconds
	stop program  = "/bin/sh /mnt/HD/HD_a2/Nas_Prog/dedupe/stop.sh /mnt/HD/HD_a2/Nas_Prog/dedupe"
	mode active
